#################################################
# Docker
#################################################
---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml
  tasks:
  
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu trusty stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker.io state=latest

    - name: Pull Jenkins Docker image
      docker_image:
        name: qxodream/alpine-tomcat-jenkins
        source: pull
        
    - name: Pull Tomcat (SHERLOCK Web Server) Docker image
      docker_image:
        name: davidcaste/alpine-tomcat
        source: pull

    - name: Create Jenkins Container
      docker_container:
        name: Jenkins
        image: davidcaste/alpine-tomcat-jenkins
        command: "{{ default_container_command }}"
        state: present
      
    - name: Create Tomcat (SHERLOCK Web Server) Container
      docker_container:
        name: SHERLOCK
        image: qxodream/alpine-tomcat-jenkins
        command: "{{ default_container_command }}"
        state: present

